apiVersion: ceph.rook.io/v1
kind: CephCluster

metadata:
  name: main
  namespace: openshift-storage

spec:
  dataDirHostPath: /var/lib/rook # under /host in CoreOS
  mon:
    #count: 3
    allowMultiplePerNode: true
  mgr:
    #count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  #crashCollector:
  #  disable: true
  #monitoring:
  #  enabled: true
  #  rulesNamespace: openshift-storage
  #network:
  #  provider: host
  cephVersion:
    # https://quay.io/repository/ceph/ceph?tab=tags
    # 16.2.6, 14.2.22
    image: quay.io/ceph/ceph:v16.2.6

    # Ceph 16 pacific https://catalog.redhat.com/software/containers/rhceph/rhceph-5-rhel8/60ec72a74a6a2c7844abe5fb?tag=all
    #image: registry.redhat.io/rhceph/rhceph-5-rhel8:5-14

    # Ceph 14 nautilus https://catalog.redhat.com/software/containers/detail/5e39df7cd70cc54b02baf33f?tag=all
    #image: registry.redhat.io/rhceph/rhceph-4-rhel8:4-59

    # Ceph 12 luminous https://catalog.redhat.com/software/containers/rhceph/rhceph-3-rhel7/5a15ec17ecb5244d5b553577?tag=all
    #image: registry.redhat.io/rhceph/rhceph-3-rhel7:3-51
  storage:
    useAllNodes: true
    useAllDevices: true
    #nodes:
    #- name: lab2
    #  devices:
    #  - name: /dev/sdc
    # config:
    #   osdsPerDevice: "1"
    #   # storeType: bluestore

---

kind: ConfigMap
apiVersion: v1

metadata:
  name: rook-config-override
  namespace: openshift-storage

data:
  config: |
    #[global]
    #osd_pool_default_size = 1
    #mon_warn_on_pool_no_redundancy = false
    #auth cluster required = none
    #auth service required = none
    #auth client required = none
    #auth supported = none
