apiVersion: v1
kind: Namespace

metadata:
  name: network-function

---

apiVersion: configsync.gke.io/v1beta1
kind: RepoSync

metadata:
  name: repo-sync # this name is required
  namespace: network-function

spec:
  sourceFormat: unstructured
  git:
    repo: $GIT_HOST/$GIT_USERNAME/$GIT_REPO.git
    dir: /namespaces/network-function
    branch: main
    auth: none

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: ns-reconciler-network-function
  namespace: network-function

subjects:
- kind: ServiceAccount
  name: ns-reconciler-network-function # created by Config Sync for the RepoSync reconciler
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
