apiVersion: ceph.rook.io/v1
kind: CephFilesystem

metadata:
  name: main
  namespace: openshift-storage

# https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md
# https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md
# https://github.com/rook/rook/blob/master/Documentation/ceph-pool-crd.md

spec:
  metadataPool:
    replicated:
      size: 1
      requireSafeReplicaSize: false
  dataPools:
  - failureDomain: osd
    replicated:
      size: 1
      requireSafeReplicaSize: false
  metadataServer:
    activeCount: 1
    activeStandby: true
