kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: edge1
networking:
  apiServerAddress: 192.168.1.11 # lab1
nodes:
- role: control-plane
  extraPortMappings:
  # see dashboard-node-port.yaml
  - containerPort: 32000
    hostPort: 32000
