apiVersion: v1
kind: Namespace

metadata:
  name: porch-ui

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: porch-ui
  namespace: porch-ui

spec:
  replicas: 1
  selector:
    matchLabels:
      app: porch-ui
  template:
    metadata:
      labels:
        app: porch-ui
    spec:
      containers:
      # See: https://console.cloud.google.com/gcr/images/kpt-dev/global/kpt-backstage-plugins/backstage-plugin-cad?project=kpt-dev
      - name: backstage
        image: gcr.io/kpt-dev/kpt-backstage-plugins/backstage-plugin-cad:v0.1.3
        ports:
        - name: http
          containerPort: 7007
        args:
        - --config
        - /etc/config/porch-ui.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: porch-ui

        # env:
        # - name: AUTH_GOOGLE_CLIENT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: cad-google-oauth-client
        #       key: client-id
        #       optional: false
        # - name: AUTH_GOOGLE_CLIENT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: cad-google-oauth-client
        #       key: client-secret
        #       optional: false

---

apiVersion: v1
kind: Service

metadata:
  name: porch-ui
  namespace: porch-ui

spec:
  selector:
    app: porch-ui
  type: NodePort
  ports:
  - port: 7007
    targetPort: http
    nodePort: 32200

---

apiVersion: v1
kind: ConfigMap

metadata:
  name: porch-ui
  namespace: porch-ui

data:
  # See:
  #   https://github.com/GoogleContainerTools/kpt-backstage-plugins/blob/main/app-config.kubernetes.yaml
  #   https://github.com/GoogleContainerTools/kpt-backstage-plugins/blob/main/app-config.yaml
  #   https://github.com/backstage/backstage/blob/master/app-config.yaml
  porch-ui.yaml: |
    app:
      baseUrl: http://localhost:32200

    organization:
      name: kpt.dev

    backend:
      baseUrl: http://localhost:32200
      cors:
        origin: http://localhost:32200

    configAsData:
      resourcesNamespace: porch-demo
