kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: $CLUSTER_NAME
networking:
  apiServerAddress: $API_ADDRESS
  apiServerPort: $API_PORT
  podSubnet: 10.97.0.0/16
  serviceSubnet: 10.197.0.0/16
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: $DASHBOARD_CONTAINER_PORT
    hostPort: $DASHBOARD_PORT
  - containerPort: 32100 # Gitea NodePort
    hostPort: 32100
